version: "3.7"

networks:
  bridge:
    driver: bridge
    name: local

services:
  remix:
    build:
      context: .
      dockerfile: Dockerfile
      network: bridge
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - bridge
    stdin_open: true
    tty: true
    environment:
      - MEMCACHIER_SERVERS=memcached:11211
    depends_on:
      - memcached
    command: sh -c "yarn build && yarn start"
  
  memcached:
    image: "memcached:alpine3.18"
    networks:
      - bridge
    container_name: lojinha_memcached
    ports:
      - "11211:11211"